#define ROCEV2_UDP_PORT 4791
#define MAX_VALUE 1023

#define OOO_PORT 152
#define REPLICA_PORT 48
#define RECIRC_REQUEST_PORT 32

#define BACKUP  2
#define REQUEST 3
#define UNFULFILLED_REQUEST 4

#define REPLICA_POOL_SIZE 200

#define REQUEST_INTERVAL 4
#define REQUEST_TIMEOUT 2
